### PR TITLE
Create NewFeature2.java

### PR DESCRIPTION
**Pull request by sonicning**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/sonicning/HelloWorld/pull/3%23issuecomment-273375208%22%2C%20%22https%3A//github.com/sonicning/HelloWorld/pull/3%23issuecomment-273456793%22%2C%20%22https%3A//github.com/sonicning/HelloWorld/pull/3%23issuecomment-273458566%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/sonicning/HelloWorld/pull/3%23issuecomment-273375208%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22added%20code%20review%20task%201%22%2C%20%22created_at%22%3A%20%222017-01-18T03%3A45%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6220120%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/sonicning%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40sonicning%20Review%20comments%22%2C%20%22created_at%22%3A%20%222017-01-18T11%3A54%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/25199099%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/sonic-developer1%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222017-01-18T12%3A04%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6220120%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/sonicning%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/sonicning%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6220120%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/sonicning'></a>

- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/sonicning/HelloWorld/pull/3#issuecomment-273375208'>General Comment</a></b>
- <a href='https://github.com/sonicning'></a> added code review task 1
- <a href='https://github.com/sonic-developer1'></a> @sonicning Review comments

<a href='https://www.codereviewhub.com/sonicning/HelloWorld/pull/3?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/sonicning/HelloWorld/pull/3?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/sonicning/HelloWorld/pull/3?approve=0'></a>&nbsp;<a href='https://github.com/sonicning/HelloWorld/pull/3'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by sonicning** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/sonicning/HelloWorld/pull/3'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by sonicning** [comment]
added code review task 1

**Comment by sonic-developer1** [comment]
@sonicning Review comments

**Review by sonic-developer1 — CHANGES_REQUESTED** [review]
@sonicning Please change the date format to "yyyy-MM-dd HH:mm"

**Comment by sonicning** [comment]
:shipit:

**Pull request merged**
